---
default: &default
  admin: jmilton
  email:
    from: isapple@JeremysMacBookPro-Work.local
    subject: "AbracaZabra Error"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default