---
default: &default
  abracazabra:
    admin: jmilton
    email:
      from: isapple@JeremysMacBookPro-Work.local
      subject: "AbracaZabra Error"
  jira:
    url: "http://localhost:8080/jira"
    project_id: 10000
    issue_id: 10000
    username: Zabbix
    password: zabbix
    email:
      from: isapple@JeremysMacBookPro-Work.local
      subject: "Zabbix Automated Daily Report"
      to:
        - isapple@JeremysMacBookPro-Work.local
      body: |-
          Good Morning,
          There %total_alerts% for %from_date% to %to_date%.
    priorities:
      blocker: 1
      critical: 2
      major: 3
      minor: 4
      standard: 10000
      trivial: 5
    resolution:
      Unresolved: -1
      Fixed: 1
      "Won't Fix": 2
      Duplicate: 3
      Incomplete: 4
      "Cannot Reproduce": 5
      Completed: 6
      Done: 7
      Passed: 8
      Failed: 9
      "Ready for Release": 10
      "Won't Release": 11
      "Won't Complete": 13
      Invalid: 14
      Assigned: 15
      Released: 16
      "False Positive": 10002
      Declined: 10000
      Complete: 10001
    statuses:
      open: 1
      resolved: 5
    type:
      Bug: 1
      Task: 3
      Epic: 13
      Improvement: 5
  zabbix:
    text_descriptions:
      average: Average
      disaster: Disaster
      high: High
      ok: OK
      problem: PROBLEM
      trigger_severity: "Trigger severity"
      trigger_status: "Trigger status"
      warning: Warning
      zabbix_id: "Original event ID"
    email:
      whitelist:
        - vamf-no-reply@va.gov
        - emm-no-reply@va.gov
        - mae-no-reply@va.gov
        - isapple@JeremysMacBookPro-Work.local

development:
  <<: *default

test:
  <<: *default

production:
  abracazabra:
    admin: jmilton
    email:
      from: isapple@JeremysMacBookPro-Work.local
      subject: "AbracaZabra Error"
      whitelist:
        - vamf-no-reply@va.gov
        - emm-no-reply@va.gov
        - mae-no-reply@va.gov
        - isapple@JeremysMacBookPro-Work.local
  jira:
    url: "http://localhost:8080/jira"
    from: isapple@JeremysMacBookPro-Work.local
    subject: "Zabbix Automated Daily Report"
    to:
      - isapple@JeremysMacBookPro-Work.local
    email:
      body: |-
          Good Morning,
          There %total_alerts% for %from_date% to %to_date%.
    project_id: 14009
    issue_id: 31
    username: zabbix
    password: Zabb1x!ServA
    priorities:
      Blocker: 1
      Critical: 2
      Major: 3
      Minor: 4
      Trivial: 5
      Standard: 6
    resolution:
      Unresolved: -1
      Fixed: 1
      "Won't Fix": 2
      Duplicate: 3
      Incomplete: 4
      "Cannot Reproduce": 5
      Completed: 6
      Done: 7
      Passed: 8
      Failed: 9
      "Ready for Release": 10
      "Won't Release": 11
      "Won't Complete": 13
      Invalid: 14
      Assigned: 15
      Released: 16
      "False Positive": 10002
      Declined: 10000
      Complete: 10001
    statuses:
      Open: 1
      "In Progress": 3
      Reopened: 4
      Resolved: 5
      Closed: 6
      Waiting: 10000
      "Under Review": 11043
  zabbix:
    text_descriptions:
      average: Average
      disaster: Disaster
      high: High
      ok: OK
      problem: PROBLEM
      trigger_severity: "Trigger severity"
      trigger_status: "Trigger status"
      warning: Warning
      zabbix_id: "Original event ID"
